---
apiVersion: v1
kind: ConfigMap
metadata:
  name: testrail-init
data:
  init.sh: |-
    #!/usr/bin/env bash

    touch /var/www/testrail/healthz
    a2enmod remoteip
    tee /etc/apache2/conf-enabled/remoteip.conf &>/dev/null <<EOF
    RemoteIPHeader X-Real-IP
    RemoteIPInternalProxy 10.0.0.0/8
    EOF
