output "cluster_name" {
  description = "Your cluster name"
  value       = local.cluster_name
}

output "cluster_endpoint" {
  description = "Endpoint for EKS control plane."
  value       = module.eks.cluster_endpoint
}

output "kubectl_config" {
  description = "kubectl config as generated by the module."
  value       = module.eks.kubeconfig
}

output "rds_cluster_endpoint" {
  description = "The cluster endpoint"
  value       = module.db.rds_cluster_endpoint
}

# database_name is not set on `aws_rds_cluster` resource if it was not specified, so can't be used in output
output "rds_cluster_database_name" {
  description = "Name for an automatically created database on cluster creation"
  value       = var.database_name
}

output "rds_cluster_master_username" {
  description = "The master username"
  value       = module.db.rds_cluster_master_username
  sensitive   = true
}

output "rds_cluster_master_password" {
  description = "The master password"
  value       = module.db.rds_cluster_master_password
  sensitive   = true
}
